config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  # mount ActionCable.server => '/cable'
  get 'transporters/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'admins#dashboard', as: :authenticated_admin_root
    end
  end

  namespace :admins do
    resources :customers do
      member do
        post 'approve_customer'
        get 'show_customer', as: :show_customer_in_load
      end
    end
    resources :transporters do
      member do
        post 'approve_transporter'
      end

      post 'create_vehicle_from_order' => "vehicles#create_vehicle_from_order"
    end
    resources :quotes do
      member do
        get 'edit_quote'
        patch 'update_quote'
        put 'cancel_quote'
      end
    end
    resources :loads do
      member do
        put 'cancel'
        put 'approve'
        get 'see_quotes'
      end
      resources :quotes, only: [] do
        member do
          put 'accept_quote'
        end
      end
      resources :trackers, only: [:index, :new, :create, :show], shallow: true
      # get 'new_from_order' => "trackers#new_from_order"
    end
    resources :payment_plans
    resources :weight_units
    resources :dimension_units
    resources :volume_units
    resources :vehicle_load_types
    resources :vehicle_types
    resources :load_types
    resources :cities
    resources :orders do
      member do
        put 'cancel'
        post 'create_vehicle'
        get 'assign_vehicle_form'
        post 'assign_vehicle'
        get 'get_address_form'
        patch 'set_address'
        patch 'dispatch_order'
        patch 'marke_as_reached'
      end

      collection do
        get 'active_orders'
        get 'processed_orders'
      end

      resources 'payments', only: [] do
        member do
          get 'customer_payment_form'
          patch 'receive_customer_payment'
        end
      end
      get 'transporter_payment_form' => 'payments#transporter_payment_form'
      post 'pay_transporter_payment' => 'payments#pay_transporter_payment'
    end
    # get 'active_orders' => 'orders#active_orders'
    # get 'active_orders' => 'orders#active_orders'
    get 'new_order_track_detail/trip/:id' => 'orders#new_order_track_detail', as: :new_order_track_detail
    post 'create_order_track_detail/trip/:id' => 'orders#create_order_track_detail', as: :create_order_track_detail
    get 'track_order/:id' => 'orders#track_order', as: :track_order

  end
  resources :admins, as: :sub_admins, :path => 'sub_admins'
  get 'admins/:id/web_notification_show', to: "admins#web_notification_show", as: :web_notification_show
  get 'get_notifyable_transporter/:load_id', to: "admins#get_notifyable_transporter", as: :get_notifyable_transporter
  get 'all_transporter_routes', to: "admins#all_transporter_routes"
  post 'send_notification_for_new_load', to: "admins#send_notification_for_new_load"
  # resources :admin  do
  #   member do
  #     post 'approve_customer/:customer_id' => 'admin#approve_customer', as: :approve_customer
  #   end
  # end

  namespace :customers do
    namespace :loads do
      resources :builds, only: [:create, :show, :update]
    end
    resources :loads do
      member do
        put 'cancel'
        put "accept_quote/:quote_id", :as => "accept_quote", :action => "accept_quote"
        get 'order'
        get 'confirmed_load'
        get 'in_transit'
        get 'track'
        get 'track_details'
        get 'quotes'
        get 'cancel_load'
        put 'dispatch_order'
        put 'marke_as_reached'
        get 'load_detail'
        get 'get_address_form'
        patch 'set_address'
        get 'track_shipment'
        get 'find_address'
      end
    end
    resources :payments, path: "quote/:quote_id/payments"
    get "payments/get_all_plans", to: "payments#get_all_plans"
    get "payments/get_form", to: "payments#get_form"
   # get "quote/:quote_id/payments/new", to: "payments#new", as: :quote_payment
  end
  devise_for :customers, controllers: {
        registrations: 'customers/registrations',
        sessions: 'customers/sessions'
  }
  devise_scope :customer do
    authenticated :customer do
      root 'customers/loads#index', as: :authenticated_customer_root
    end
  end


  resources :customers, only: :show do
    member do
      get 'change_password'
      put 'update_password'
      get 'send_otp'
      get 'otp_authentication'
      post 'verify_phone'
    end

    collection do
      get 'web_notifications'
    end
    resources :bank_account_details
  end

  devise_for :transporters, controllers: {
        registrations: 'transporters/registrations',
        sessions: 'transporters/sessions'
  }
  devise_scope :transporter do
    authenticated :transporter do
      root 'transporters/quotes#index', as: :authenticated_transporter_root
    end
  end

  namespace :transporters do
    resources :vehicles
    resources :transporter_routers, except: :new
    resources :quotes do
      member do
        get 'draft'
      end
    end
    post 'load/:id/add_to_favorite', as: :add_to_favorite, to: "quotes#add_to_favorite"

    resources :orders, only: [:show, :index] do
      member do
        get 'vehicle_list'
        post 'assign_vehicle'
        delete 'discard_vehicle'
        # put 'dispatch_order'
        put 'cancel_order'
        get 'track'
        get 'track_details'
        get 'payment_info'
        get 'cancel'
        get 'order_details'
        get 'order_statistic'
      end

      # get '/dispatch' => :ready_to_dispatch_load, as: :ready_to_dispatch_load
      # get '/list_vehicle' => :list_vehicle, as: :list_vehicle
      # post '/assign_vehicle' => :assign_vehicle, as: :assign_vehicle
      # delete '/discard_vehicle' => :discard_vehicle_assignmnet, as: :discard_vehicle_assignmnet
      # post '/dispatch_load' => :dispatch_load, as: :dispatch_load
      # get '/in_transit' => :in_transit, as: :in_transit
      # get '/cancel_order' => :cancel_order, as: :cancel_order
    end

    # controller :tracking do
    #   scope 'load/:id/' do
    #     get 'load_tracking' => :load_tracking, as: :load_tracking
    #     get 'track_details' => :track_details, as: :track_details
    #   end
    # end

    # resources :orders, only: [] do
    #   member do
    #     get 'payment_info'
    #   end
    # end
  end

  resources :transporters, only: :show do
    member do
      get 'change_password'
      put 'update_password'
      get 'send_otp'
      get 'otp_authentication'
      post 'verify_phone'
    end
    collection do
      get 'web_notifications'
    end
    resources :bank_account_details
  end

  post 'authenticate_customer_for_account_existence' => 'landing#authenticate_customer_for_account_existence'
  root 'landing#transport_landing'
  # Default path if no routes match
  # match '*path' => redirect('/'), via: :get
end

app/views/admins/_form.html.erb
<%= form_for sub_admin, url: :sub_admins do |f| %>
  <div class="panel panel-default">
    <ul class="list-group">
      <li class="list-group-item">
        <div class="row custom-form-row-full">
          <div class="col-sm-2">
            <p class="feature_title form-label-title">
              Email
            </p>
          </div>
          <div class="col-sm-2">
            <div class="form-group">
              <%= f.email_field :email, class: 'form-control custom-form-control', placeholder: 'Enter Email'  %>
              <div style="color: rgb(204, 0, 0)"><%= show_errors(sub_admin, :email) %></div>
            </div>
          </div>
          <div class="col-sm-2">
            <p class="feature_title form-label-title">
              Password
            </p>
          </div>
          <div class="col-sm-2">
            <div class="form-group">
              <%= f.text_field :password, class: 'form-control custom-form-control', placeholder: 'Enter Password'  %>
              <div style="color: rgb(204, 0, 0)"><%= show_errors(sub_admin, :password) %></div>
            </div>
          </div>
          <div class="col-sm-4 add-more-right">
            <%= f.button :submit, class: 'btn custom-btn custom_btn custom-add-bordered-btn m-none' do %>
              <span class='glyphicon glyphicon-plus'></span> Save
            <% end %>
          </div>
        </div>
      </li>
    </ul>
  </div>
<% end %>

app/views/admins/_load_and_quote_header.html.erb
<div class="col-sm-6 add-more-right">
  <%= link_to "Load",admins_loads_path, class: 'btn custom-head-add-bordered-btn' %>
  <%= link_to "Quotes",admins_quotes_path, class: 'btn custom-head-add-bordered-btn' %>
  <%= link_to "Active", active_orders_admins_orders_path, class: 'btn custom-head-add-bordered-btn' %>
  <%= link_to "History", processed_orders_admins_orders_path, class: 'btn custom-head-add-bordered-btn' %>
</div>

app/views/admins/_web_notification.html.erb
<a href="<%= linkable?(web_notification) %>">
  <div class="dashboard_menu_box">
    <strong>TITLE</strong> : <%= web_notification.title %><br>
		<strong>MESSAGE</strong> :<br>
    <% case web_notification.notifiable_type %>
    <% when "Inquiry" %>
	    <%= render 'admins/web_notification_templates/inquiry', web_notification: web_notification %>
    <% when "Customer", "Transporter" %>
	    <%= render 'admins/web_notification_templates/registration', web_notification: web_notification %>
    <% when "Load" %>
	    <%= render 'admins/web_notification_templates/load', web_notification: web_notification %>
    <% when "Quote" %>
      <%= render 'admins/web_notification_templates/quote', web_notification: web_notification %>
    <% end %>
    <strong>Submitted at:</strong> : <%= time_ago_in_words(web_notification.created_at).match("month|year").blank? ? time_ago_in_words(web_notification.created_at, include_seconds: true) : web_notification.created_at %><br>
  </div>
</a>

app/views/admins/dashboard.html.erb
<!-- <table>
  <%# @customers.each do |customer| %>
    <tr>
      <td><%#= customer.email.presence || customer.ph_no %></td>
      <td><%#= customer.approved %></td>
      <%# if params[:approved] %>
      	<td><%#= link_to "Approve", approve_customer_admin_path(current_admin, customer), method: :post %></td>
      <%# end %>
    </tr>
   <%# end %>
</table> -->
            <!-- Main page content including header-->



                 <!-- page title row starts here-->
                <div class="row page-title-row custom-page-title-row">
                    <div class="col-xs-12 breadcrums-wrapper">
                        <ol class="breadcrumb">
                            <li><a href="<%= authenticated_admin_root_path %>">Home</a></li>
                            <li class="active">Dashboard</li>
                        </ol>
                    </div>
                </div>
                <!-- page title row ends here-->

                <div class="row">
                    <div class="col-xs-12 col-sm-12">
                        <div class="page_title">
                            <h2 class="mt-10">Welcome Admin!</h2>
                        </div>
                    </div>
                </div>

                <div class="row dashboard_menu_box_wrap">
                  <a href="<%= admins_customers_path %>" class="col-sm-6 col-md-4 col-lg-3">
                    <div class="dashboard_menu_box">
                     <span>
                         <i class="fa fa-users" aria-hidden="true"></i>
                     </span>
                     <div>Customers</div>
                    </div>
                  </a>
                  <a href="<%= admins_transporters_path %>" class="col-sm-6 col-md-4 col-lg-3">
                    <div class="dashboard_menu_box">
                     <span>
                         <i class="fa fa-ship" aria-hidden="true"></i>
                     </span>
                     <div>Transporter</div>
                    </div>
                  </a>
                  <!-- <a href="view_students.html" class="col-sm-6 col-md-4 col-lg-3">
                      <div class="dashboard_menu_box">
                         <span>
                             <i class="fa fa-graduation-cap" aria-hidden="true"></i>
                         </span> 
                         <div>Students</div>
                     </div>
                  </a>
                  <a href="view_schools.html" class="col-sm-6 col-md-4 col-lg-3">
                      <div class="dashboard_menu_box">
                         <span>
                             <i class="fa fa-building" aria-hidden="true"></i>
                         </span> 
                         <div>Schools</div>
                     </div>
                  </a>
                  <a href="class.html" class="col-sm-6 col-md-4 col-lg-3">
                      <div class="dashboard_menu_box">
                         <span>
                             <i class="fa fa-leanpub" aria-hidden="true"></i>
                         </span> 
                         <div>Classes</div>
                     </div>
                  </a>

                  <a href="session.html" class="col-sm-6 col-md-4 col-lg-3">
                      <div class="dashboard_menu_box">
                         <span>
                             <i class="fa fa-book" aria-hidden="true"></i>
                         </span> 
                         <div>Sessions</div>
                     </div>
                  </a>
                  <a href="fees_charges.html" class="col-sm-6 col-md-4 col-lg-3">
                      <div class="dashboard_menu_box">
                         <span>
                             <i class="fa fa-money" aria-hidden="true"></i>
                         </span> 
                         <div>Fees Charges</div>
                     </div>
                  </a>
                  <a href="view_students.html" class="col-sm-6 col-md-4 col-lg-3">
                      <div class="dashboard_menu_box large_menu_box">
                         <span>
                             <i class="fa fa-money" aria-hidden="true"></i>
                         </span> 
                         <div>Fees <br> Collections</div>
                     </div>
                  </a>
                  <a href="roles.html" class="col-sm-6 col-md-4 col-lg-3">
                      <div class="dashboard_menu_box">
                         <span>
                             <i class="fa fa-user-plus" aria-hidden="true"></i>
                         </span> 
                         <div>Roles</div>
                     </div>
                  </a>

                    <a href="id_types.html" class="col-sm-6 col-md-4 col-lg-3">
                        <div class="dashboard_menu_box large_menu_box">
                           <span>
                               <i class="fa fa-file-text" aria-hidden="true"></i>
                           </span> 
                           <div>Identification <br> Types</div>
                       </div>
                    </a> -->
                  <a href="<%= admins_payment_plans_path %>" class="col-sm-6 col-md-4 col-lg-3">
                    <div class="dashboard_menu_box">
                      <span>
                        <i class="fa fa-money" aria-hidden="true"></i>
                      </span>
                      <div>Payments</div>
                    </div>
                  </a>
                  <a href="#" class="col-sm-6 col-md-4 col-lg-3">
                    <div class="dashboard_menu_box">
                      <span>
                        <i class="fa fa-list-alt" aria-hidden="true"></i>
                      </span>
                      <div>Reports</div>
                   </div>
                  </a>
                  <a href="<%= admins_loads_path %>" class="col-sm-6 col-md-4 col-lg-3">
                    <div class="dashboard_menu_box">
                      <span>
                        <i class="fa fa-cubes" aria-hidden="true"></i>
                      </span>
                      <div>Loads And Quotes</div>
                   </div>
                  </a>
                    <!-- <a href="calendar_view.html" class="col-sm-6 col-md-4 col-lg-3">
                        <div class="dashboard_menu_box">
                           <span>
                               <i class="fa fa-calendar" aria-hidden="true"></i>
                           </span>
                           <div>Calendar</div>
                       </div>
                    </a> -->

                </div>
            </div>

            <!-- Footer-->

<script type="text/javascript">
  $("#leftbtn").click(function(){

    // if ($(window).width() > 1300) {
    //      $('.dashboard_menu_box').find("span").css({
    //       'marginLeft' :'20px',
    //       width:'70px',
    //       hight:'70px',
    //       lineHeight:'70px',
    //     });
    // }
    // else{
    //     $('.dashboard_menu_box').find("span").css({
    //       'marginLeft' :'40px',
    //       width:'75px',
    //       hight:'75px',
    //       lineHeight:'75px',
    //     });
    // }

  }); 
</script>

app/views/admins/index.html.erb
<% provide(:title, "Sub Admin") %>
<%= render 'shared/admin_breadcrumbs' %>

<div class="row">
  <div class="col-xs-12 col-sm-12 load_form">
  	<%= render 'form', sub_admin: @sub_admin %>
  </div>
</div>
<div class="row table-contents-wrapper table-records-wrapper">
  <div class="col-xs-12 revenue-table-wrapper">
    <!-- <div class="row search-wrapper">
      <div class="col-sm-6 revenue-search-box">
        <form class="form-inline revenue-table-form view-record-form">
          <label>Search</label>
          <input type="text" class="form-control search-box" name="search" id="search">
        </form>
      </div>
    </div> -->
    <div class="table-responsive">
      <table class="table table-hover revenue-table">
        <thead class="bg-color-pink">
          <tr>
            <th>Id</th>
            <th>Email</th>
            <th class="width-10">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @sub_admins.each do |sub_admin| %>
            <tr>
              <td><%= sub_admin.id %></td>
              <td><%= sub_admin.email %></td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<% title "SubAdmin" %>
<%= render 'form' %>

app/views/admins/web_notification_show.html.erb
<%= render partial: 'web_notification', collection: @web_notifications  %>