config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  # mount ActionCable.server => '/cable'
  get 'transporters/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'admins#dashboard', as: :authenticated_admin_root
    end
  end

  namespace :admins do
    resources :customers do
      member do
        post 'approve_customer'
        get 'show_customer', as: :show_customer_in_load
      end
    end
    resources :transporters do
      member do
        post 'approve_transporter'
      end

      post 'create_vehicle_from_order' => "vehicles#create_vehicle_from_order"
    end
    resources :quotes do
      member do
        get 'edit_quote'
        patch 'update_quote'
        put 'cancel_quote'
      end
    end
    resources :loads do
      member do
        put 'cancel'
        put 'approve'
        get 'see_quotes'
      end
      resources :quotes, only: [] do
        member do
          put 'accept_quote'
        end
      end
      resources :trackers, only: [:index, :new, :create, :show], shallow: true
      # get 'new_from_order' => "trackers#new_from_order"
    end
    resources :payment_plans
    resources :weight_units
    resources :dimension_units
    resources :volume_units
    resources :vehicle_load_types
    resources :vehicle_types
    resources :load_types
    resources :cities
    resources :orders do
      member do
        put 'cancel'
        post 'create_vehicle'
        get 'assign_vehicle_form'
        post 'assign_vehicle'
        get 'get_address_form'
        patch 'set_address'
        patch 'dispatch_order'
        patch 'marke_as_reached'
      end

      collection do
        get 'active_orders'
        get 'processed_orders'
      end

      resources 'payments', only: [] do
        member do
          get 'customer_payment_form'
          patch 'receive_customer_payment'
        end
      end
      get 'transporter_payment_form' => 'payments#transporter_payment_form'
      post 'pay_transporter_payment' => 'payments#pay_transporter_payment'
    end
    # get 'active_orders' => 'orders#active_orders'
    # get 'active_orders' => 'orders#active_orders'
    get 'new_order_track_detail/trip/:id' => 'orders#new_order_track_detail', as: :new_order_track_detail
    post 'create_order_track_detail/trip/:id' => 'orders#create_order_track_detail', as: :create_order_track_detail
    get 'track_order/:id' => 'orders#track_order', as: :track_order

  end
  resources :admins, as: :sub_admins, :path => 'sub_admins'
  get 'admins/:id/web_notification_show', to: "admins#web_notification_show", as: :web_notification_show
  get 'get_notifyable_transporter/:load_id', to: "admins#get_notifyable_transporter", as: :get_notifyable_transporter
  get 'all_transporter_routes', to: "admins#all_transporter_routes"
  post 'send_notification_for_new_load', to: "admins#send_notification_for_new_load"
  # resources :admin  do
  #   member do
  #     post 'approve_customer/:customer_id' => 'admin#approve_customer', as: :approve_customer
  #   end
  # end

  namespace :customers do
    namespace :loads do
      resources :builds, only: [:create, :show, :update]
    end
    resources :loads do
      member do
        put 'cancel'
        put "accept_quote/:quote_id", :as => "accept_quote", :action => "accept_quote"
        get 'order'
        get 'confirmed_load'
        get 'in_transit'
        get 'track'
        get 'track_details'
        get 'quotes'
        get 'cancel_load'
        put 'dispatch_order'
        put 'marke_as_reached'
        get 'load_detail'
        get 'get_address_form'
        patch 'set_address'
        get 'track_shipment'
        get 'find_address'
      end
    end
    resources :payments, path: "quote/:quote_id/payments"
    get "payments/get_all_plans", to: "payments#get_all_plans"
    get "payments/get_form", to: "payments#get_form"
   # get "quote/:quote_id/payments/new", to: "payments#new", as: :quote_payment
  end
  devise_for :customers, controllers: {
        registrations: 'customers/registrations',
        sessions: 'customers/sessions'
  }
  devise_scope :customer do
    authenticated :customer do
      root 'customers/loads#index', as: :authenticated_customer_root
    end
  end


  resources :customers, only: :show do
    member do
      get 'change_password'
      put 'update_password'
      get 'send_otp'
      get 'otp_authentication'
      post 'verify_phone'
    end

    collection do
      get 'web_notifications'
    end
    resources :bank_account_details
  end

  devise_for :transporters, controllers: {
        registrations: 'transporters/registrations',
        sessions: 'transporters/sessions'
  }
  devise_scope :transporter do
    authenticated :transporter do
      root 'transporters/quotes#index', as: :authenticated_transporter_root
    end
  end

  namespace :transporters do
    resources :vehicles
    resources :transporter_routers, except: :new
    resources :quotes do
      member do
        get 'draft'
      end
    end
    post 'load/:id/add_to_favorite', as: :add_to_favorite, to: "quotes#add_to_favorite"

    resources :orders, only: [:show, :index] do
      member do
        get 'vehicle_list'
        post 'assign_vehicle'
        delete 'discard_vehicle'
        # put 'dispatch_order'
        put 'cancel_order'
        get 'track'
        get 'track_details'
        get 'payment_info'
        get 'cancel'
        get 'order_details'
        get 'order_statistic'
      end

      # get '/dispatch' => :ready_to_dispatch_load, as: :ready_to_dispatch_load
      # get '/list_vehicle' => :list_vehicle, as: :list_vehicle
      # post '/assign_vehicle' => :assign_vehicle, as: :assign_vehicle
      # delete '/discard_vehicle' => :discard_vehicle_assignmnet, as: :discard_vehicle_assignmnet
      # post '/dispatch_load' => :dispatch_load, as: :dispatch_load
      # get '/in_transit' => :in_transit, as: :in_transit
      # get '/cancel_order' => :cancel_order, as: :cancel_order
    end

    # controller :tracking do
    #   scope 'load/:id/' do
    #     get 'load_tracking' => :load_tracking, as: :load_tracking
    #     get 'track_details' => :track_details, as: :track_details
    #   end
    # end

    # resources :orders, only: [] do
    #   member do
    #     get 'payment_info'
    #   end
    # end
  end

  resources :transporters, only: :show do
    member do
      get 'change_password'
      put 'update_password'
      get 'send_otp'
      get 'otp_authentication'
      post 'verify_phone'
    end
    collection do
      get 'web_notifications'
    end
    resources :bank_account_details
  end

  post 'authenticate_customer_for_account_existence' => 'landing#authenticate_customer_for_account_existence'
  root 'landing#transport_landing'
  # Default path if no routes match
  # match '*path' => redirect('/'), via: :get
end

app/views/shared/_admin_footer.html.erb
<div class="col-xs-12 footer_wrap">
  All Rights Reserved | ©Transport.co.in
</div>

app/views/shared/_admin_header.html.erb
<div class="header_wrap navbar-fixed-top">
  <div class="menu_icon" class="hamburger is-closed" id="leftbtn">
      <i class="fa fa-bars"></i>
  </div>

  <div class="logo">
      <a href="<%= authenticated_admin_root_path %>"><img src="/assets/admin/trance-logo.png" alt=""></a>
  </div>
  <%= link_to web_notification_show_path(current_admin) do %>
    <span id="web_notification_bell">
      <i class="fa fa-bell">
        <div id="admin_web_notification_count">
          <%# if current_admin.web_notifications.count > 0 %>
            <%= render '/shared/admin_web_notification_bedge' %>
          <%# end %>
        </div>
      </i>
    </span>
  <% end %>
  <div class="my_account">
    <div class="btn-group account_wrap">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <span class=""><i class="fa fa-user"></i></span> <span class="u_name hidden-xs"> <%= current_admin.email %> </span><span class="caret"></span>
      </button>
      <ul class="dropdown-menu account_dropdown" role="menu">
        <!-- <li><a href="profile.html"><span><i class="fa fa-user"></i></span> My Profile</a></li> -->
        <li>
        <%= link_to destroy_admin_session_path, method: :delete do %>
        	<span><i class="fa fa-power-off"></i></span> Logout
        <% end %>
      </ul>
    </div>
  </div>

  <!-- <a class="icons-toggle-btn" title="More options"><i class="glyphicon glyphicon-chevron-down"></i></a>
  <div class="head-select">
    <select class="form-control custom-form-control" name="selectboxExample" id="selectboxExample">
      <option value=""> Select School</option>
      <option value=""> School One </option>
      <option value=""> School Two </option>
      <option value=""> School Three </option>
    </select>
  </div> -->
</div>
<!-- <%#= link_to "Sign out", destroy_admin_session_path, method: :delete %> |
<%#= link_to "All Customer", authenticated_admin_root_path%> |
<%#= link_to "Customer awaiting approval", authenticated_admin_root_path(:approved => "false") %> |
<%# if current_admin.kind_of?(Admin) %>
	<%#= link_to "Sub Admins", sub_admin_index_path %> |
<%# end %>
<%#= link_to "Weight Unit", admin_weight_units_path %> |
<%#= link_to "Dimention Unit", admin_dimention_units_path %> |
<%#= link_to "Volume Unit", admin_volume_units_path %> |
<%#= link_to "Load Type", admin_load_types_path %> |
<%#= link_to "Vehicle Type", admin_vehicle_types_path %> |
<%#= link_to "Vehicle Load Type", admin_vehicle_load_types_path %>
<%#= link_to "Payment Plan", admin_payment_plans_path %>
 -->

app/views/shared/_admin_sidebar.html.erb
<ul class="sidebar_wrap navbar navbar-inverse navbar-fixed-top col-xs-12" id="sidebar-wrapper" role="navigation">
  <li class="active col-xs-12 ">
    <a href="<%= authenticated_admin_root_path %>" class="active_nav main-link" title="Dashboard">
      <span><i class="fa fa-tachometer"></i><span>Dashboard</span></span>
    </a>
  </li>

  <li class="col-xs-12">
    <%= link_to sub_admins_path, class: 'main-link col-xs-12', title:'Customer' do %>
      <span><i class="fa fa-users"></i><span>Sub Admin</span></span>
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_customers_path, class: 'main-link col-xs-12', title:'Customer' do %>
      <span><i class="fa fa-users"></i><span>Customers</span></span>
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_transporters_path, class: 'main-link col-xs-12', title: 'Transporter' do%>
      Transporters
      <!-- <span><i class="fa fa-graduation-cap"></i><span>Transporter</span></span> -->
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_payment_plans_path, class: 'main-link col-xs-12', title: 'Transporter' do%>
       <span><i class="fa fa-money" aria-hidden="true"></i><span>Payments</span></span> 
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_loads_path, class: 'main-link col-xs-12', title: 'Transporter' do%>
      Loads And Quotes
      <!-- <span><i class="fa fa-graduation-cap"></i><span>Transporter</span></span> -->
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_load_types_path, class: 'main-link', title: 'Load Type' do%>
      LoadTypes
      <!-- <span><i class="fa fa-building"></i><span>LoadTypes</span></span> -->
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_dimension_units_path, class: 'main-link', title: 'Dimention Unit' do%>
      Dimention Unit
      <!-- <span><i class="fa fa-leanpub"></i><span>Dimention Unit</span></span> -->
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_volume_units_path, class: 'main-link', title: 'Volume Unit' do%>
      Volume Unit
      <!-- <span><i class="fa fa-book"></i><span>Volume Unit</span></span> -->
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_weight_units_path, class: 'main-link', title: 'Weight Unit' do %>
      Weight Unit<!-- <span><i class="fa fa-money"></i><span>Weight Unit</span></span> -->
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_vehicle_load_types_path, class: 'main-link', title: 'Vehicle Load Type' do %>
      Vehicle Load Type<!-- <span><i class="fa fa-money"></i><span>Vehicle Load Type</span></span> -->
    <% end %>
  </li>

  <li class="col-xs-12">
    <%= link_to admins_vehicle_types_path, class: 'main-link', title: 'Vehicle Type' do%>
      Vehicle Type<!-- <span><i class="fa fa-truck"></i><span>Vehicle Type</span></span> -->
    <% end %>
  </li>
  <li class="col-xs-12">
    <%= link_to admins_cities_path, class: 'main-link', title: 'City' do%>
      City<!-- <span><i class="fa fa-truck"></i><span>Vehicle Type</span></span> -->
    <% end %>
  </li>

  <!-- <li class="col-xs-12">
    <a href="id_types.html" class="main-link" title="IdentificationTypes">
      <span><i class="fa fa-file-text"></i><span>ID Types</span></span>
    </a>
  </li>

  <li class="col-xs-12">
    <a href="fees_type.html" class="main-link" title="FeesTypes">
      <span><i class="fa fa-credit-card"></i><span>Fees Types</span></span>
    </a>
  </li>
  <li class="col-xs-12">
    <a href="#" class="main-link" title="Reports">
      <span><i class="fa fa-list-alt"></i><span>Reports</span></span>
    </a>
  </li>
  <li class="col-xs-12">
    <a href="calendar_view.html" class="main-link" title="Calendar">
      <span><i class="fa fa-calendar"></i><span>Calendar</span></span>
    </a>
  </li> -->

</ul>

app/views/shared/_admin_web_notification_bedge.html.erb
<span class="badge badge-notify <%=current_admin.web_notifications.count <= 0 ? 'hidden' : '' %>" id="admin-all"><%= current_admin.web_notifications.count %></span>

app/views/shared/_customer_header.html.erb
<!-- <head>
	<link rel="icon" href="/assets/customer/favicon.png" type="image/x-icon" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body id="top"> -->
	<div id="corder1" class="navbar-fixed top-nav">
    <nav class="theme-bg" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href="#" class="brand-logo logo" style="display: block;"><img src="/assets/customer/logo.png" alt="Transport logo"></a>
        <ul id="dropdown1" class="dropdown-content">
          <li><%= link_to "Change password", change_password_customer_path(current_customer) %></li>
          <li><%= link_to "Profile", customer_path(current_customer) %></li>
          <li><%= link_to "Sign out", destroy_customer_session_path, method: :delete %></li>
        </ul>
        <ul class="right hide-on-med-and-down">
          <li>
            <a class="waves-effect waves-light" href="<%= web_notifications_customers_path %>">
              <img src="/assets/customer/bel-3.png" alt="load icon" style="position: relative;top:5px;">
              <div id="customer_web_notification_count">
                <% if current_customer.web_notifications.count > 0 %>
                  <%= render "/shared/customer_web_notification_bedge" %>
                <% end %>
              </div>
            </a>
          </li>
          <li><%= link_to "MY LOADS", authenticated_customer_root_path,class: "waves-effect waves-light" %></li>
          <li><a class="waves-effect waves-light" href="#">TRACK</a></li>
          <li><a class='dropdown-button' href='#' data-activates='dropdown1' style="padding-top: 1px;"><%= current_customer.email.present? ? current_customer.email : current_customer.ph_no %></a></li>
        </ul>
        <ul id="dropdown2" class="dropdown-content">
          <li><%= link_to "Change password", change_password_customer_path(current_customer) %></li>
          <li><%= link_to "Profile", customer_path(current_customer) %></li>
          <li><%= link_to "Sign out", destroy_customer_session_path, method: :delete %></li>
        </ul>
        <ul id="nav-mobile" class="side-nav">
          <li><a class="waves-effect waves-light" href="#"><i class="large material-icons">person_pin</i></a></li>
          <li><%= link_to "MY LOADS", authenticated_customer_root_path,class: "waves-effect waves-light" %></li>
          <li><a class="waves-effect waves-light" href="#">TRACK</a></li>
          <li><a class='dropdown-button' href='#' data-activates='dropdown2'><%= current_customer.email.present? ? current_customer.email : current_customer.ph_no %></a></li>
         </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>
  </div>
<!-- </body> -->
<%#= javascript_include_tag 'http://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js' %>
<%#= javascript_include_tag 'http://code.jquery.com/jquery-2.1.2.min.js' %>

<!-- <%#= link_to "Sign out", destroy_customer_session_path, method: :delete %> | -->
<!-- <%#= link_to "Profile", customer_path(current_customer) %> | -->
<!-- <%#= link_to "Change password", change_password_customer_path(current_customer) %> | -->
<!-- Welcome, <%#= current_customer.email %> -->

app/views/shared/_customer_load_header.html.erb
<!-- <%#= link_to "LOADS POSTED", authenticated_customer_root_path %> | -->
<%#= link_to "ACTIVE", authenticated_customer_root_path(status: "active") %>
<!-- <%#= link_to "LOADS POSTED", authenticated_customer_root_path %> | -->
<!-- <%#= link_to "ACTIVE", authenticated_customer_root_path(status: "active") %> | -->
<%#= link_to "HISTORY", authenticated_customer_root_path(status: "processed") %>

app/views/shared/_customer_web_notification_bedge.html.erb
<span class="badge badge-notify" >
	<%= current_customer.web_notifications.count %>
</span>

app/views/shared/_default_footer.html.erb
<footer class="page-footer footer-color">
    <div class="container">
        <div class="row" style="margin-bottom:0px;">
            <div class="col l6">
                <div class="col s12 logo"><img src="/assets/customer/logo.png" alt="Transport logo"></div>
                <!-- <P class="col s12">Transport.co.in is a platform that helps you find,<br>compare and book trucks to move your from one<br>place to another.</P> -->
                <p>Copyrights, Maruti 3PL Pvt. Ltd.</p>
            </div>
            <div class="col l3">
                <h6><a href="<%= (transporter_signed_in? || customer_signed_in?) ? "#" : new_transporter_session_path %>" class="waves-effect waves-light">Transporter Login</a></h6>
                <h6><a href="<%= (transporter_signed_in? || customer_signed_in?) ? "#" : new_customer_session_path %>">Customer Login</a></h6>
                <h6><a href="#">CONTACT US</a></h6>
                <h6>FAQ</h6>
            </div>
            <div class="col l3">
                <h6 style="color: #888;">ADDRESS</h6>
                <h6>S-96,RAVINDRA BHAWAN,</h6>
                <h6>IIT ROORKEE,</h6>
                <h6>UTTARAKHAND - 247667</h6>
                <h6>INDIA</h6>
                <h6>MOB +91-9192939495</h6>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_default_header.html.erb
        <div class="navbar-fixed top-nav">
            <nav class="theme-bg" role="navigation">
                <div class="nav-wrapper container">
                    <ul class="left hide-on-med-and-down links">
                        <li><a href="javascript:;"><img src="/assets/customer/logo.png" alt="Transport logo" alt="logo" style="width: 145px;margin-top: 7px;margin-bottom: -8px;"></a></li>
                        <li><a href="javascript:;"><i class="tiny material-icons left"><img src="/assets/customer/phone.png" alt="phone"></i> <small>(+91)</small> 78-78-50-50-50 </a></li>
                        <li><a href="javascript:;"><i class="tiny material-icons left"><img src="/assets/customer/massage.png" alt="massage"></i>hello@transport.co.in</a></li>
                    </ul>
                    <a id="logo-container" href="#" class="brand-logo logo"><img src="/assets/customer/logo.png" alt="Transport logo"></a>
                    <ul id="dropdown1" class="dropdown-content">
                      <li><%= link_to "CUSTOMER",new_customer_session_path,class: "theme-text" %></li>
                      <li><%= link_to "TRANSPORTER",new_transporter_session_path,class: "theme-text" %></li>
                      <!-- <a href="#!" class="theme-text">CUSTOMER</a></li> -->
                      <!-- <li><a href="#!" class="theme-text">TRANSPORTER</a></li> -->
                    </ul>
                    <ul class="right hide-on-med-and-down">
                        <li><a class="waves-effect waves-light" href="#about">ABOUT US</a></li>
                        <li><a class="waves-effect waves-light" href="#why">WHY US</a></li>
                        <li><a class="waves-effect waves-light" href="#how-work">HOW IT WORK</a></li>
                        <li><a class="waves-effect waves-light" href="#contact">CONTACT US</a></li>
                        <li><a class='dropdown-button' href='#' data-activates='dropdown1' style="padding-top: 1px;">LOGIN</a></li>
                        <!--<li><a class="waves-effect waves-light modal-trigger" href="#modal1">LOGIN</a></li>-->
                    </ul>
                    <ul id="dropdown2" class="dropdown-content">
                      <li><a href="#!" class="theme-text">CUSTOMER</a></li>
                      <li><a href="#!" class="theme-text">TRANSPORTER</a></li>
                    </ul>
                    <ul id="nav-mobile" class="side-nav">
                        <li><a class="waves-effect waves-light" href="#about">ABOUT US</a></li>
                        <li><a class="waves-effect waves-light" href="#why">WHY US</a></li>
                        <li><a class="waves-effect waves-light" href="#how-work">HOW IT WORK</a></li>
                        <li><a class="waves-effect waves-light" href="#contact">CONTACT US</a></li>
                        <li><a class='dropdown-button' href='#' data-activates='dropdown2'>LOGIN</a></li>
                        <!--<li><a class="waves-effect waves-light modal-trigger" href="#modal1">LOGIN</a></li>-->
                    </ul>
                    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
                </div>
            </nav>
        </div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type,message| %>
  <div class="alert custom-alert alert-<%= message_type %>" >
  	<%= message unless message.blank? %> 
  	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  </div>
<% end %>

app/views/shared/_headers.html.erb
<% if admin_signed_in? %>
	<%= render 'shared/admin_header' %>
<% elsif customer_signed_in? %>
	<%= render 'shared/customer_header' %>
	<%= render 'shared/customer_load_header' %>
<% elsif transporter_signed_in? %>
	<%= render 'shared/transporter_header' %>
	<%#= render 'shared/transporter_quote_header' %>
<% else %>
	<%= render 'shared/default_header' %>
	
	<!-- <%#= link_to "Log in as Customer", new_customer_session_path %> | -->
	<!-- <%#= link_to "Sign up as Customer", new_customer_registration_path %> | -->
	<!-- <%#= link_to "Log in as Transporter", new_transporter_session_path %> | -->
	<!-- <%#= link_to "Sign up as Transporter", new_transporter_registration_path %><br /> -->
	
<% end %>

app/views/shared/_transporter_header.html.erb
<%= stylesheet_link_tag "transporters/style" %>
<div class="navbar-fixed top-nav">
  <nav class="theme-bg" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo logo" style="display: block;"><img src="/assets/transporter/logo.png" alt="Transport logo"></a>
      <ul id="dropdown1" class="dropdown-content">
        <li><%= link_to "Change password", change_password_transporter_path(current_transporter) %></li>
        <li><%= link_to "Profile", transporter_path(current_transporter) %></li>
        <li><%= link_to "Add new routes", transporters_transporter_routers_path %></li>
        <li><%= link_to "Add new vehicle", transporters_vehicles_path %></li>
        <li><%= link_to "Sign out", destroy_transporter_session_path, method: :delete %></li>
      </ul>
      <ul class="right hide-on-med-and-down head-menu">
        <li>
          <a class="waves-effect waves-light" href="<%= web_notifications_transporters_path %>">
            <img src="/assets/customer/bel-3.png" alt="load icon" style="position: relative;top:5px;">
            <div id="transporter_web_notification_count">
              <% if current_transporter.web_notifications.count > 0 %>
                <%= render "/shared/transporter_web_notification_bedge" %>
              <% end %>
            </div>
          </a>
        </li>
        <li><a class="waves-effect waves-light menu-item active" href="<%= authenticated_transporter_root_path %>">MY TRIPS</a></li>
        <li><a class="waves-effect waves-light menu-item" href="#">TRACK</a></li>
        <li><a class="dropdown-button menu-item" href='#' data-activates='dropdown1' style="padding-top: 1px;"><%= current_transporter.email %></a></li>
      </ul>
      <!-- <ul id="dropdown2" class="dropdown-content">
        <li><%#= link_to "Change password", change_password_transporter_path(current_transporter) %></li>
        <li><%#= link_to "Profile", transporter_path(current_transporter) %></li>
        <li><%#= link_to "Add new routes", new_transporters_transporter_router_path %></li>
        <li><%#= link_to "Sign out", destroy_transporter_session_path, method: :delete %></li>
      </ul> -->
      <ul id="nav-mobile" class="side-nav">
        <li><a class="waves-effect waves-light" href="#"><i class="large material-icons">person_pin</i></a></li>
        <li><a class="waves-effect waves-light" href="<%= authenticated_transporter_root_path %>">MY TRIPS</a></li>
        <li><a class="waves-effect waves-light" href="#">TRACK</a></li>
        <li><a class='dropdown-button' href='#' data-activates='dropdown2'><%= current_transporter.email %></a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</div>

app/views/shared/_transporter_quote_header.html.erb
<div class="black-bg">
  <div class="row">
    <div class="col l8 offset-l2 m10 offset-m1 s12">
      <ul class="menu top-menu">
        <li class="menu-item top-menu-item item"><%= link_to authenticated_transporter_root_path,class: "#{!params[:status].present? ? 'active' : ''}" do %><span class="icon-menu load"></span>Loads Available<% end %></li>
        <li class="menu-item top-menu-item item"><%= link_to transporters_orders_path(status: "active"),class: "#{params[:status]}" do %><span class="icon-menu actve"></span>Active<% end %></li>
        <li class="menu-item top-menu-item item"><%= link_to transporters_orders_path(status: "processed"),class: "#{params[:status] == 'processed' ? 'active' : ''}" do%><span class="icon-menu history"></span>History<% end %></li>
        <li class="menu-item top-menu-item item"><a href="profile.html"><span class="icon-menu profile"></span>Profile</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- <%#= link_to "LOADS AVAILABLE", authenticated_transporter_root_path %> | -->
<!-- <%#= link_to "ACTIVE", transporters_orders_path(status: "active") %> | -->
<!-- <%#= link_to "HISTORY", transporters_orders_path(status: "processed") %> -->

app/views/shared/_transporter_web_notification_bedge.html.erb
<span class="badge badge-notify" >
	<%= current_transporter.web_notifications.count %>
</span>