config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  # mount ActionCable.server => '/cable'
  get 'transporters/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'admins#dashboard', as: :authenticated_admin_root
    end
  end

  namespace :admins do
    resources :customers do
      member do
        post 'approve_customer'
        get 'show_customer', as: :show_customer_in_load
      end
    end
    resources :transporters do
      member do
        post 'approve_transporter'
      end

      post 'create_vehicle_from_order' => "vehicles#create_vehicle_from_order"
    end
    resources :quotes do
      member do
        get 'edit_quote'
        patch 'update_quote'
        put 'cancel_quote'
      end
    end
    resources :loads do
      member do
        put 'cancel'
        put 'approve'
        get 'see_quotes'
      end
      resources :quotes, only: [] do
        member do
          put 'accept_quote'
        end
      end
      resources :trackers, only: [:index, :new, :create, :show], shallow: true
      # get 'new_from_order' => "trackers#new_from_order"
    end
    resources :payment_plans
    resources :weight_units
    resources :dimension_units
    resources :volume_units
    resources :vehicle_load_types
    resources :vehicle_types
    resources :load_types
    resources :cities
    resources :orders do
      member do
        put 'cancel'
        post 'create_vehicle'
        get 'assign_vehicle_form'
        post 'assign_vehicle'
        get 'get_address_form'
        patch 'set_address'
        patch 'dispatch_order'
        patch 'marke_as_reached'
      end

      collection do
        get 'active_orders'
        get 'processed_orders'
      end

      resources 'payments', only: [] do
        member do
          get 'customer_payment_form'
          patch 'receive_customer_payment'
        end
      end
      get 'transporter_payment_form' => 'payments#transporter_payment_form'
      post 'pay_transporter_payment' => 'payments#pay_transporter_payment'
    end
    # get 'active_orders' => 'orders#active_orders'
    # get 'active_orders' => 'orders#active_orders'
    get 'new_order_track_detail/trip/:id' => 'orders#new_order_track_detail', as: :new_order_track_detail
    post 'create_order_track_detail/trip/:id' => 'orders#create_order_track_detail', as: :create_order_track_detail
    get 'track_order/:id' => 'orders#track_order', as: :track_order

  end
  resources :admins, as: :sub_admins, :path => 'sub_admins'
  get 'admins/:id/web_notification_show', to: "admins#web_notification_show", as: :web_notification_show
  get 'get_notifyable_transporter/:load_id', to: "admins#get_notifyable_transporter", as: :get_notifyable_transporter
  get 'all_transporter_routes', to: "admins#all_transporter_routes"
  post 'send_notification_for_new_load', to: "admins#send_notification_for_new_load"
  # resources :admin  do
  #   member do
  #     post 'approve_customer/:customer_id' => 'admin#approve_customer', as: :approve_customer
  #   end
  # end

  namespace :customers do
    namespace :loads do
      resources :builds, only: [:create, :show, :update]
    end
    resources :loads do
      member do
        put 'cancel'
        put "accept_quote/:quote_id", :as => "accept_quote", :action => "accept_quote"
        get 'order'
        get 'confirmed_load'
        get 'in_transit'
        get 'track'
        get 'track_details'
        get 'quotes'
        get 'cancel_load'
        put 'dispatch_order'
        put 'marke_as_reached'
        get 'load_detail'
        get 'get_address_form'
        patch 'set_address'
        get 'track_shipment'
        get 'find_address'
      end
    end
    resources :payments, path: "quote/:quote_id/payments"
    get "payments/get_all_plans", to: "payments#get_all_plans"
    get "payments/get_form", to: "payments#get_form"
   # get "quote/:quote_id/payments/new", to: "payments#new", as: :quote_payment
  end
  devise_for :customers, controllers: {
        registrations: 'customers/registrations',
        sessions: 'customers/sessions'
  }
  devise_scope :customer do
    authenticated :customer do
      root 'customers/loads#index', as: :authenticated_customer_root
    end
  end


  resources :customers, only: :show do
    member do
      get 'change_password'
      put 'update_password'
      get 'send_otp'
      get 'otp_authentication'
      post 'verify_phone'
    end

    collection do
      get 'web_notifications'
    end
    resources :bank_account_details
  end

  devise_for :transporters, controllers: {
        registrations: 'transporters/registrations',
        sessions: 'transporters/sessions'
  }
  devise_scope :transporter do
    authenticated :transporter do
      root 'transporters/quotes#index', as: :authenticated_transporter_root
    end
  end

  namespace :transporters do
    resources :vehicles
    resources :transporter_routers, except: :new
    resources :quotes do
      member do
        get 'draft'
      end
    end
    post 'load/:id/add_to_favorite', as: :add_to_favorite, to: "quotes#add_to_favorite"

    resources :orders, only: [:show, :index] do
      member do
        get 'vehicle_list'
        post 'assign_vehicle'
        delete 'discard_vehicle'
        # put 'dispatch_order'
        put 'cancel_order'
        get 'track'
        get 'track_details'
        get 'payment_info'
        get 'cancel'
        get 'order_details'
        get 'order_statistic'
      end

      # get '/dispatch' => :ready_to_dispatch_load, as: :ready_to_dispatch_load
      # get '/list_vehicle' => :list_vehicle, as: :list_vehicle
      # post '/assign_vehicle' => :assign_vehicle, as: :assign_vehicle
      # delete '/discard_vehicle' => :discard_vehicle_assignmnet, as: :discard_vehicle_assignmnet
      # post '/dispatch_load' => :dispatch_load, as: :dispatch_load
      # get '/in_transit' => :in_transit, as: :in_transit
      # get '/cancel_order' => :cancel_order, as: :cancel_order
    end

    # controller :tracking do
    #   scope 'load/:id/' do
    #     get 'load_tracking' => :load_tracking, as: :load_tracking
    #     get 'track_details' => :track_details, as: :track_details
    #   end
    # end

    # resources :orders, only: [] do
    #   member do
    #     get 'payment_info'
    #   end
    # end
  end

  resources :transporters, only: :show do
    member do
      get 'change_password'
      put 'update_password'
      get 'send_otp'
      get 'otp_authentication'
      post 'verify_phone'
    end
    collection do
      get 'web_notifications'
    end
    resources :bank_account_details
  end

  post 'authenticate_customer_for_account_existence' => 'landing#authenticate_customer_for_account_existence'
  root 'landing#transport_landing'
  # Default path if no routes match
  # match '*path' => redirect('/'), via: :get
end

app/controllers/admins/transporters_controller.rb
class Admins::TransportersController < ApplicationController
	before_action :set_transporter, only: [:show, :edit, :update, :destroy, :approve_transporter]
	before_action :authenticate_admin!
	
	def index
		@transporters = params[:approved].nil? ? Transporter.find_by_account_status : Transporter.find_by_account_status(params[:approved])
	end

	def new
		@transporter = Transporter.new
		@bank_account_detail = @transporter.bank_account_details.build
	end

	def create
		@transporter = Transporter.new(transporter_params)
		@transporter[:approved] = true
		@transporter[:ph_no_verified] = true
		if @transporter.save
			redirect_to admins_transporters_path,notice: "Transporter created successfully!"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @transporter.update_attributes(transporter_params)
			redirect_to admins_transporters_path, notice: "Transporter updated successfully!"
		else
			render 'edit'		
		end	
	end

	def show
	end

	def destroy
		@transporter.destroy
		redirect_to admins_transporters_path, notice: "Transporter deleted successfully!"
	end

	def approve_transporter
	    @transporter.approve_resource
	    redirect_to :back
  	end

	private
	 	def set_transporter
	 		begin
	 			@transporter = Transporter.friendly.find(params[:id])
	 		rescue Exception => e
	 			redirect_to :back, notice: "transporter is not found"
	 		end
	 	end

	 	def transporter_params
			params.require(:transporter).permit(:email, :ph_no_verified, :approved ,:password,:password_confirmation,:name,:ph_no,:company_name,:address_detail,bank_account_details_attributes: [:id,:bank_name,:branch_name,:account_holder_name,:account_number,:ifsc_code,:_destroy])
		end
end

app/controllers/transporters/orders_controller.rb
class Transporters::OrdersController < ApplicationController
  before_action :authenticate_transporter!
  before_action :get_order, except: :index
	# before_action :set_load

	def index
	  @orders = current_transporter.accessible_orders(params[:status])
	end

	def show
		respond_to :js
	end

	# def ready_to_dispatch_load
	# end

	def vehicle_list
		respond_to :js
	end

	def assign_vehicle
		@load.assign_vehicles.destroy_all
		@load.assign_vehicles << Vehicle.find(params[:assign_vehicle])
		redirect_to transporters_order_path(@order), notice: "Assign successfully!"
		rescue ActiveRecord::AssociationTypeMismatch, ActiveRecord::RecordNotFound
			flash.now[:notice] = "Please select vehicles."
			render "vehicle_list"
		rescue ActiveRecord::RecordInvalid => e
			flash.now[:notice] = e.message.split(":")[1]
			render "vehicle_list"
	end

	def discard_vehicle
		@load.assign_vehicles.destroy_all
		redirect_to transporters_order_path(@order), notice: "Assignment removed!"
	end

	# def dispatch_order
	# 	return redirect_to transporters_list_vehicle_path(@load), notice: "Assign Vehicle." if @load.assign_vehicles.blank?
	# 	@load.dispatch
	# 	redirect_to transporters_in_transit_path
	# end

	# def in_transit
	# 	return redirect_to transporters_ready_to_dispatch_load_path(@load) if @load.confirmed?
	# 	render 'ready_to_dispatch_load'
	# end

	def cancel_order
		if @load.confirmed_order.cancel_order()
			redirect_to authenticated_transporter_root_path, notice: "Order canceled."
		else
			redirect_to authenticated_transporter_root_path, notice: "Order not canceled."
		end
	end

	def track
		@trips = @load.trips
		respond_to :js
	end

	def track_details
		@trip = Trip.find(params[:trip])
	end

	def payment_info
	end

	def cancel
		@order = Order.find(params[:id])
		respond_to :js
	end

	def order_details
		@order = Order.find(params[:id])
		respond_to :js
	end

	def order_statistic
		@order = Order.find(params[:id])
		@trips = @load.trips
		@trip = @trips.first
		respond_to :js
	end
	private

	def get_order
		@order = Order.find(params[:id])
		@load = @order.load
		@quote = @order.quote
		@assign_vehicles = @load.assign_vehicles
	end

	def set_load
		@load ||= Load.includes(:accepted_quote, :assign_vehicles, trips: :vehicle).friendly.find(params[:id])
		@quote ||= @load.accepted_quote
	end

end

app/controllers/transporters/quotes_controller.rb
class Transporters::QuotesController < ApplicationController
  before_action :authenticate_transporter!
  before_action :get_quote, only: [:show, :draft, :edit, :update, :destroy]
  before_action :get_load, only: [:show, :edit, :draft]

  def index
  	@loads = Load.includes(:load_type, :vehicle_load_type, :vehicle_type, :quotes, :transporters).posted
    # if ["active", "processed"].include?(params[:status])
	   #  @orders = current_transporter.confirmed_loads(params[:status])
    # else
	   #  @loads = current_transporter.accessible_loads
    # end
  	@quotes = current_transporter.quotes
  end

  def new
    @load = Load.friendly.find(params[:load_id])
    @vehicle_load_types = VehicleLoadType.all
		@quote = current_transporter.quotes.new
    respond_to :js
  end

  def draft
  	# render 'new'
    @vehicle_load_types = VehicleLoadType.all
    respond_to :js
  end

  def create
    exit
    @quote = current_transporter.quotes.new(quote_params)
    if @quote.save(validate: !params[:draft].present?)
      flash[:success] = t("transporter.quote.save", action: params[:commit].present? ? "created" : "drafted" )
      # @quote.send("#{params[:commit].present? ? 'submitted' : 'drafted'}!")
      @quote.update_attribute(:status, params[:commit].present? ? :submitted : :drafted )
      redirect_to transporters_quotes_path
    # else
    #   render "new"
    end
  end

  def show
    respond_to :js
  end

  def edit
     @vehicle_load_types = VehicleLoadType.all
     respond_to :js
  end

  def update
  	if @quote.update_attributes(quote_params)
  		flash[:success] = t("transporter.quote.save", action: params[:commit].present? ? "updated" : "drafted" )
  		@quote.send("#{params[:commit].present? ? 'submitted' : 'drafted'}!")
  		redirect_to transporters_quotes_path
  	end
  end

  def destroy
    exit
  	if @quote.destroy
  		flash[:success] = t("transporter.quote.soft_delete")
  		redirect_to transporters_quotes_path
  	end
  end

  def add_to_favorite
    load = Load.includes(:favorite_loads).friendly.find(params[:id])
    favorite_load = load.favorite_loads.select{ |load| load.transporter_id == current_transporter.id }[0]
    if favorite_load.nil?
      load.transporters << current_transporter
    else
      favorite_load.destroy
    end
    # render json: :success
    redirect_back(fallback_location: "/")
  end

  private

  def get_quote
  	@quote ||= Quote.includes(:load).friendly.find(params[:id])
  end

  def get_load
  	@load ||= @quote.load
  end

  def quote_params
  	params.require(:quote).permit(:load_id, :offered_date, :offered_vehicle_load_type_id, :offered_vehicle_type_id, :offered_vehicle_quantity, :offered_price)
  end

end

app/controllers/transporters/registrations_controller.rb
class Transporters::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
  respond_to :html, :js

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    # super(resource)
    send_otp_transporter_path(resource)
  end
end

app/controllers/transporters/sessions_controller.rb
class Transporters::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    transporter = Transporter.find_by_login(params[:transporter][:login])
    if transporter.nil? || transporter.ph_no_verified?
      self.resource = warden.authenticate!(auth_options)
      set_flash_message!(:notice, :signed_in)
      sign_in(resource_name, resource)
      yield resource if block_given?
        respond_with resource, location: after_sign_in_path_for(resource)
    else
      redirect_to send_otp_transporter_path(transporter), method: :post
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admins/transporters_helper.rb
module Admins::TransportersHelper
	def link_to_remove_fields(name,f)
		f.hidden_field(:_destroy) + link_to_function(name,"remove_fields(this)" ,class: "btn custom-btn custom_btn custom-add-bordered-btn m-none")
	end

	def link_to_add_fields(name, f, association)
	  new_object = f.object.class.reflect_on_association(association).klass.new
	  fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	    render(association.to_s.singularize + "_fields", :f => builder)
  	  end
  	link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")",class: "btn custom-btn custom_btn custom-add-bordered-btn m-none")
	end
end

app/helpers/transporters/orders_helper.rb
module Transporters::OrdersHelper
end

app/helpers/transporters/quotes_helper.rb
module Transporters::QuotesHelper
end

app/helpers/transporters/tracking_helper.rb
module Transporters::TrackingHelper
end

app/helpers/transporters/transporter_routers_helper.rb
module Transporters::TransporterRoutersHelper
end

app/helpers/transporters/vehicles_helper.rb
module Transporters::VehiclesHelper
end

app/helpers/transporters_helper.rb
module TransportersHelper

	def quoted_load?(load, quotes)
		quotes.collect {|q| break [q] if q.load_id == load.id }.compact.blank? ? false : true
	end

	def load_quote(load, quotes)
		quotes.collect {|q| break [q] if q.load_id == load.id }.compact.first
	end

end

app/views/transporters/_basic_detail.html.erb
<div class="row">
  <div class="col s5 m4 l3 mobile-view">
    <p><strong>Email <span class="text-right colon"> : </span></strong></p>
  </div>
  <div class="col s7 m8 l9 mobile-view">
    <p>
      <%= transporter.email %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col s5 m4 l3 mobile-view">
    <p><strong>Name <span class="text-right colon"> : </span></strong></p>
  </div>
  <div class="col s7 m8 l9 mobile-view">
    <p>
      <%= transporter.name || "-" %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col s5 m4 l3 mobile-view">
    <p><strong>Phone Number <span class="text-right colon"> : </span></strong></p>
  </div>
  <div class="col s7 m8 l9 mobile-view">
    <p>
      <%= transporter.ph_no || "-" %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col s5 m4 l3 mobile-view">
    <p><strong>Company Name <span class="text-right colon"> : </span></strong></p>
  </div>
  <div class="col s7 m8 l9 mobile-view">
    <p>
      <%= transporter.company_name || "-" %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col s5 m4 l3 mobile-view">
    <p><strong>Address detail <span class="text-right colon"> : </span></strong></p>
  </div>
  <div class="col s7 m8 l9 mobile-view">
    <p>
      <%= transporter.address_detail || "-" %>
    </p>
  </div>
</div>

app/views/transporters/_web_notification.html.erb
<div class="detail-box custom-box custom-box-wrap">
  <a data-remote="true" href="<%= linkable?(web_notification) %>">
    <div class="row" style="font-size: 0.85rem;">
      <div><strong>TITLE:</strong> <%= web_notification.title %></div>
      <div><strong>MESSAGE:</strong></div>
    </div>
    <div class="row">
      <% case web_notification.notifiable_type %>
      <% when "Load" %>
        <%= render 'transporters/web_notification_templates/load', web_notification: web_notification %>
      <% when "Quote" %>
        <%= render 'transporters/web_notification_templates/quote', web_notification: web_notification %>
      <% end %>
      <strong>Submitted at:</strong> : <%= time_ago_in_words(web_notification.created_at).match("month|year").blank? ? time_ago_in_words(web_notification.created_at, include_seconds: true) : web_notification.created_at %><br>
    </div>
  </a>
<div>

app/views/transporters/change_password.html.erb
<main>
  <div id="my-order" class="main-page">
    <!-- first tab -->
    <div id="test1" class="col s12 full-content-wrap">
      <div class="container">
        <div class="row">
          <div class="col s12">
            <div class="outer_box">
              <div class="row">
                <div class="col s12 m12 l12">
                  <div class="custom-box-wrap">
                    <div class="box_header">
                      <div class="col s6 text-left theme-text box_header_title">Change Password</div>
                    </div>
                    <div class="box_content" id="user_basic_detail">
                      <%= form_for(@transporter, url: update_password_transporter_path(@transporter), html: { method: :put }) do |f| %>

                        <div class="input-field col s12 error-log">
                          <%= f.password_field :password, autocomplete: "off", placeholder: "Enter new password", class: "validate" %>
                          <!-- <label for="number" class="theme-text actives">From</label> -->
                          <%= f.label :password, class: "theme-text actives" %> <br />
                            <em>Please Enter Valid City</em>
                        </div>

                        <div class="input-field col s12 error-log">
                          <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "Confirm new password", class: "validdate" %>
                          <%= f.label :password_confirmation, class: "theme-text actives" %><br />
                        </div>

                        <div class="input-field col s12 error-log">
                          <i>(we need your current password to confirm your changes)</i>
                          <%= f.password_field :current_password, autocomplete: "off", placeholder: "Enter Your Current Password", class: "validate" %>
                          <%= f.label :current_password, class: "theme-text actives" %> <br />
                        </div>

                        <div class="actions col s12 left-align">
                          <%= f.submit "Update", class: "waves-effect waves-light btn-flat theme-bg white-text butons center-align" %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/transporters/dashboard.html.erb
<h1>Transporters#dashboard</h1>
<p>Find me in app/views/transporters/dashboard.html.erb</p>

app/views/transporters/otp_authentication.html.erb
<style>
  .notice,.alert{
    display:none;
  }
</style>
<%= stylesheet_link_tag "transporters/materialize" %>
<%= stylesheet_link_tag "transporters/style" %>
<div class="section no-pad-bot main-page" id="home">
  <div class="container" style="overflow: visible;">
    <h1 class="header center"><img src="/assets/transporter/transport-logo.png" alt="transport"></h1>
    <div class="row">
      <div class="col m8 offset-m2 l6 offset-l3 s12 center-form-box">
        <div class="login_title_wrap">
        	<div>Enter the code that was sent to you</div>
        </div>
        <div class="home-from login_form clearfix col s12">
        	<%= form_tag(verify_phone_transporter_path,:method => :post) do %>
        		<div>
              <div class="row">
                <div class="col s12">
                  <div class="card-panel theme-bg">
                  	<p class="errmsg"><%= notice %><%= alert %></p>
                  </div>
                </div>
              </div>
              <div class="input-field col s12 error-log">
              	<%= text_field_tag :otp_code ,nil,class: "validate" %>
              </div>
              <div class="login_button">
              	<button type="submit" class="btn-floating btn-large waves-effect waves-light theme-bg posi"><i class=" large material-icons">navigate_next</i></button>
              </div>
              <div class="col s12 form_footer">
                <div class="term_reset">
                	<%= link_to "Resend OTP", send_otp_transporter_path %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div>
	<%= render 'shared/default_footer' %>
</div>
<!-- <h2>Enter the code that was sent to you</h2>

<%#= form_tag(verify_phone_transporter_path,:method => :post) do %>
  <%#= text_field_tag :otp_code %>
  <%#= submit_tag "Submit" %>
<%# end %>

<%#= link_to "Resend OTP", send_otp_transporter_path %> -->

app/views/transporters/show.html.erb
<main>
  <div id="my-order" class="main-page">
    <!-- first tab -->
    <div id="test1" class="col s12 full-content-wrap">
      <div class="container">
        <div class="row">
          <div class="col s12">
            <div class="outer_box">
              <div class="row">
                <div class="col s12 m12 l12">
                  <div class="custom-box-wrap">
                    <div class="box_header">
                      <div class="col s6 text-left theme-text box_header_title">Basic Detail</div>
                      <div class="col s6 right-align">
                        <%= link_to "EDIT", edit_transporter_registration_path, class: "waves-effect waves-light right-align btn-flat theme-bg white-text center-align butons modal-trigger", remote: true %>
                          <!-- <a id="" href="#modal_edit_profile" class="waves-effect waves-light right-align btn-flat theme-bg white-text center-align butons modal-trigger">EDIT</a> -->
                      </div>
                    </div>
                    <div class="box_content" id="user_basic_detail">
                      <%= render 'basic_detail', transporter: @transporter %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="outer_box">
              <div class="row">
                <div class="col s12 m12 l12">
                  <div class="box_header">
                    <div class="col s6 text-left theme-text box_header_title">Bank Details</div>
                    <div class="col s6 right-align">
                      <%= link_to "Add new", new_transporter_bank_account_detail_path(current_transporter), class: "waves-effect waves-light right-align btn-flat theme-bg white-text center-align butons modal-trigger", remote: true %>
                    </div>
                  </div>
                  <div class="box_content" id="bank_detail_list">
                    <% if @bank_details.present? %>
                      <%= render(@bank_details, resource: current_transporter) %>
                    <% else %>
                      Bank detail not provide
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>



















<!-- <h3>Basic details :</h3>
email : <%#= @transporter.email %><br>
name : <%#= @transporter.name || "-" %><br>
phone number : <%#= @transporter.ph_no || "-" %><br>
Company name : <%#= @transporter.company_name || "-" %><br>
Address detail : <%#= @transporter.address_detail || "-" %><br>

<%#= link_to "Edit", edit_transporter_registration_path %><br>
<%#= link_to "Add new route", new_transporters_transporter_router_path %>
<h3>Bank details :( <%#= link_to "Add new", new_transporter_bank_account_detail_path(current_transporter) %> )</h3>
<%#= render @bank_details, resource: current_transporter  %>
 -->

app/views/transporters/web_notifications.html.erb
<%= render partial: 'web_notification', collection: @web_notifications  %>