config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  # mount ActionCable.server => '/cable'
  get 'transporters/dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'admins#dashboard', as: :authenticated_admin_root
    end
  end

  namespace :admins do
    resources :customers do
      member do
        post 'approve_customer'
        get 'show_customer', as: :show_customer_in_load
      end
    end
    resources :transporters do
      member do
        post 'approve_transporter'
      end

      post 'create_vehicle_from_order' => "vehicles#create_vehicle_from_order"
    end
    resources :quotes do
      member do
        get 'edit_quote'
        patch 'update_quote'
        put 'cancel_quote'
      end
    end
    resources :loads do
      member do
        put 'cancel'
        put 'approve'
        get 'see_quotes'
      end
      resources :quotes, only: [] do
        member do
          put 'accept_quote'
        end
      end
      resources :trackers, only: [:index, :new, :create, :show], shallow: true
      # get 'new_from_order' => "trackers#new_from_order"
    end
    resources :payment_plans
    resources :weight_units
    resources :dimension_units
    resources :volume_units
    resources :vehicle_load_types
    resources :vehicle_types
    resources :load_types
    resources :cities
    resources :orders do
      member do
        put 'cancel'
        post 'create_vehicle'
        get 'assign_vehicle_form'
        post 'assign_vehicle'
        get 'get_address_form'
        patch 'set_address'
        patch 'dispatch_order'
        patch 'marke_as_reached'
      end

      collection do
        get 'active_orders'
        get 'processed_orders'
      end

      resources 'payments', only: [] do
        member do
          get 'customer_payment_form'
          patch 'receive_customer_payment'
        end
      end
      get 'transporter_payment_form' => 'payments#transporter_payment_form'
      post 'pay_transporter_payment' => 'payments#pay_transporter_payment'
    end
    # get 'active_orders' => 'orders#active_orders'
    # get 'active_orders' => 'orders#active_orders'
    get 'new_order_track_detail/trip/:id' => 'orders#new_order_track_detail', as: :new_order_track_detail
    post 'create_order_track_detail/trip/:id' => 'orders#create_order_track_detail', as: :create_order_track_detail
    get 'track_order/:id' => 'orders#track_order', as: :track_order

  end
  resources :admins, as: :sub_admins, :path => 'sub_admins'
  get 'admins/:id/web_notification_show', to: "admins#web_notification_show", as: :web_notification_show
  get 'get_notifyable_transporter/:load_id', to: "admins#get_notifyable_transporter", as: :get_notifyable_transporter
  get 'all_transporter_routes', to: "admins#all_transporter_routes"
  post 'send_notification_for_new_load', to: "admins#send_notification_for_new_load"
  # resources :admin  do
  #   member do
  #     post 'approve_customer/:customer_id' => 'admin#approve_customer', as: :approve_customer
  #   end
  # end

  namespace :customers do
    namespace :loads do
      resources :builds, only: [:create, :show, :update]
    end
    resources :loads do
      member do
        put 'cancel'
        put "accept_quote/:quote_id", :as => "accept_quote", :action => "accept_quote"
        get 'order'
        get 'confirmed_load'
        get 'in_transit'
        get 'track'
        get 'track_details'
        get 'quotes'
        get 'cancel_load'
        put 'dispatch_order'
        put 'marke_as_reached'
        get 'load_detail'
        get 'get_address_form'
        patch 'set_address'
        get 'track_shipment'
        get 'find_address'
      end
    end
    resources :payments, path: "quote/:quote_id/payments"
    get "payments/get_all_plans", to: "payments#get_all_plans"
    get "payments/get_form", to: "payments#get_form"
   # get "quote/:quote_id/payments/new", to: "payments#new", as: :quote_payment
  end
  devise_for :customers, controllers: {
        registrations: 'customers/registrations',
        sessions: 'customers/sessions'
  }
  devise_scope :customer do
    authenticated :customer do
      root 'customers/loads#index', as: :authenticated_customer_root
    end
  end


  resources :customers, only: :show do
    member do
      get 'change_password'
      put 'update_password'
      get 'send_otp'
      get 'otp_authentication'
      post 'verify_phone'
    end

    collection do
      get 'web_notifications'
    end
    resources :bank_account_details
  end

  devise_for :transporters, controllers: {
        registrations: 'transporters/registrations',
        sessions: 'transporters/sessions'
  }
  devise_scope :transporter do
    authenticated :transporter do
      root 'transporters/quotes#index', as: :authenticated_transporter_root
    end
  end

  namespace :transporters do
    resources :vehicles
    resources :transporter_routers, except: :new
    resources :quotes do
      member do
        get 'draft'
      end
    end
    post 'load/:id/add_to_favorite', as: :add_to_favorite, to: "quotes#add_to_favorite"

    resources :orders, only: [:show, :index] do
      member do
        get 'vehicle_list'
        post 'assign_vehicle'
        delete 'discard_vehicle'
        # put 'dispatch_order'
        put 'cancel_order'
        get 'track'
        get 'track_details'
        get 'payment_info'
        get 'cancel'
        get 'order_details'
        get 'order_statistic'
      end

      # get '/dispatch' => :ready_to_dispatch_load, as: :ready_to_dispatch_load
      # get '/list_vehicle' => :list_vehicle, as: :list_vehicle
      # post '/assign_vehicle' => :assign_vehicle, as: :assign_vehicle
      # delete '/discard_vehicle' => :discard_vehicle_assignmnet, as: :discard_vehicle_assignmnet
      # post '/dispatch_load' => :dispatch_load, as: :dispatch_load
      # get '/in_transit' => :in_transit, as: :in_transit
      # get '/cancel_order' => :cancel_order, as: :cancel_order
    end

    # controller :tracking do
    #   scope 'load/:id/' do
    #     get 'load_tracking' => :load_tracking, as: :load_tracking
    #     get 'track_details' => :track_details, as: :track_details
    #   end
    # end

    # resources :orders, only: [] do
    #   member do
    #     get 'payment_info'
    #   end
    # end
  end

  resources :transporters, only: :show do
    member do
      get 'change_password'
      put 'update_password'
      get 'send_otp'
      get 'otp_authentication'
      post 'verify_phone'
    end
    collection do
      get 'web_notifications'
    end
    resources :bank_account_details
  end

  post 'authenticate_customer_for_account_existence' => 'landing#authenticate_customer_for_account_existence'
  root 'landing#transport_landing'
  # Default path if no routes match
  # match '*path' => redirect('/'), via: :get
end

app/models/quote.rb
class Quote < ApplicationRecord
  acts_as_paranoid
  extend FriendlyId
  friendly_id :transporter_name, use: [:slugged, :history]
  enum status: { drafted: 0, submitted: 1, withdrawed: 2, accepted: 3 }
  enum quotes_by: { admin: 0, customer: 1 }

  belongs_to :transporter
  belongs_to :load
  belongs_to :vehicle_load_type, foreign_key: "offered_vehicle_load_type_id"
  belongs_to :vehicle_type, foreign_key: "offered_vehicle_type_id"
  has_many :customers_payments, dependent: :destroy
  has_many :transporters_payments, dependent: :destroy
  has_one :admin_next_receivable_payment, -> { where('customers_payments.status = ?', 0) }, class_name: 'CustomersPayment'
  has_one :order, dependent: :destroy
  has_many :generated_notifications, as: :notifiable, class_name: "WebNotification"

  # after_commit -> { SendNotificationJob.perform_later(type: self.class.name, action: "create", notified_via: ["web"], object: self) },
  #   if: -> {exit if !status.nil?}#if: -> { status_previously_changed? && (load_status_previous_change <=> ["drafted", "submitted"]) == 0 }
  after_commit -> {
    puts "#{status_previous_change} : #{status_previously_changed?}"
    SendNotificationJob.perform_later(type: self.class.name, action: "create", notified_via: ["web", "email", "sms"], object: self) if status_previously_changed? && ((status_previous_change <=> [nil, "submitted"]) == 0 || (status_previous_change <=> ["drafted", "submitted"]) == 0)
    SendNotificationJob.perform_later(type: self.class.name, action: "accepted", notified_via: ["web", "email", "sms"], object: self) if status_previously_changed? && (status_previous_change <=> ["submitted", "accepted"]) == 0
    set_quote_info if submitted?
  }

  after_commit -> {
    SendNotificationJob.perform_later(type: self.class.name, action: "edited", notified_via: ["web", "email", "sms"], object: self) if !status_previously_changed? && submitted? && (!deleted? || !destroyed?) && previous_changes.except("slug", "updated_at", "quotes_on", "quotes_by").present?
  }, on: :update

  attr_accessor :submit_status

  validates :offered_date,:offered_vehicle_load_type_id,:offered_vehicle_type_id,:offered_vehicle_quantity,:offered_price,presence:true

  def self.quotes_by_status(status)
    statuses.keys.include?(status) ? where(status: status) : where(status: statuses.keys)
  end

  def transporter_name
  	self.transporter.name
  end

  def should_generate_new_friendly_id?
    !self.transporter.name? || self.transporter.name?
  end

  # def set_status(status)
  #   self.send("#{set_status}!")
  #   # TODO : Set SMS, email notification : Quote : create
  # end

  def set_quote_info
    if quotes_on.nil?
      self.quotes_on = Time.zone.now
      self.customer!
    end
  end

  def remain_receive_payments
    customers_payments.pending
  end

  def remain_paid_payments
    # customers_payments.pending
  end

  def receive_payments
    customers_payments.paid.map(&:amount).sum
  end

  def paid_payments
    transporters_payments.paid.map(&:amount).sum
  end

  def admin_next_payable_payment
    offered_price - transporters_payments.where(status: [:paid]).sum(:amount)
  end

end

app/controllers/admins/quotes_controller.rb
class Admins::QuotesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_load, only: [:accept_quote]
  before_action :set_quote, only: [:show, :edit,:update,:cancel_quote,:accept_quote]

	def index
		# @quotes =  Quote.includes(:transporter,:vehicle_load_type,:vehicle_type,load: [:customer,:load_type,:vehicle_type]).all
		@quotes =  Quote.includes(:transporter,:vehicle_load_type,:vehicle_type,load: [:customer,:load_type,:vehicle_type]).quotes_by_status(params[:status])
		# @accepted_quote = @load.quotes.where(status: "accepted" ).count
	end

	def show
		@load = @quote.load
	end

	def edit
	end

	def update
		if @quote.update_attributes(quote_params)
			redirect_to admins_quotes_path, notice: "Quote updated."
		else
			render 'edit'
  	end
	end

	def quotes_details
		@quotes = Quote.all
	end

	def edit_quote
		@quote = Quote.friendly.find(params[:id])
	end

	def update_quote
		@quote = Quote.friendly.find(params[:id])
		@quote.update_attributes(quote_params)
		redirect_to admins_quotes_quotes_details_path,notice: "Quote updated"
	end

	def cancel_quote
		@quote.destroy
		redirect_to admins_quotes_path, notice: "Quote canceled."
	end

	def accept_quote
		@quote.accepted!
		@load.confirmed!
		redirect_to see_quotes_admins_load_path(@load.id), notice: "Quote accepted."
	end

	private

	  def set_load
	  	@load ||= Load.friendly.find(params[:load_id])
	  end

	  def set_quote
	  	 @quote ||= Quote.friendly.find(params[:id])
	  end
	  
	  def quote_params
	  	params.require(:quote).permit(:offered_date, :offered_vehicle_load_type_id, :offered_vehicle_type_id, :offered_vehicle_quantity, :offered_price)
	  end
end

app/controllers/transporters/quotes_controller.rb
class Transporters::QuotesController < ApplicationController
  before_action :authenticate_transporter!
  before_action :get_quote, only: [:show, :draft, :edit, :update, :destroy]
  before_action :get_load, only: [:show, :edit, :draft]

  def index
  	@loads = Load.includes(:load_type, :vehicle_load_type, :vehicle_type, :quotes, :transporters).posted
    # if ["active", "processed"].include?(params[:status])
	   #  @orders = current_transporter.confirmed_loads(params[:status])
    # else
	   #  @loads = current_transporter.accessible_loads
    # end
  	@quotes = current_transporter.quotes
  end

  def new
    @load = Load.friendly.find(params[:load_id])
    @vehicle_load_types = VehicleLoadType.all
		@quote = current_transporter.quotes.new
    respond_to :js
  end

  def draft
  	# render 'new'
    @vehicle_load_types = VehicleLoadType.all
    respond_to :js
  end

  def create
    exit
    @quote = current_transporter.quotes.new(quote_params)
    if @quote.save(validate: !params[:draft].present?)
      flash[:success] = t("transporter.quote.save", action: params[:commit].present? ? "created" : "drafted" )
      # @quote.send("#{params[:commit].present? ? 'submitted' : 'drafted'}!")
      @quote.update_attribute(:status, params[:commit].present? ? :submitted : :drafted )
      redirect_to transporters_quotes_path
    # else
    #   render "new"
    end
  end

  def show
    respond_to :js
  end

  def edit
     @vehicle_load_types = VehicleLoadType.all
     respond_to :js
  end

  def update
  	if @quote.update_attributes(quote_params)
  		flash[:success] = t("transporter.quote.save", action: params[:commit].present? ? "updated" : "drafted" )
  		@quote.send("#{params[:commit].present? ? 'submitted' : 'drafted'}!")
  		redirect_to transporters_quotes_path
  	end
  end

  def destroy
    exit
  	if @quote.destroy
  		flash[:success] = t("transporter.quote.soft_delete")
  		redirect_to transporters_quotes_path
  	end
  end

  def add_to_favorite
    load = Load.includes(:favorite_loads).friendly.find(params[:id])
    favorite_load = load.favorite_loads.select{ |load| load.transporter_id == current_transporter.id }[0]
    if favorite_load.nil?
      load.transporters << current_transporter
    else
      favorite_load.destroy
    end
    # render json: :success
    redirect_back(fallback_location: "/")
  end

  private

  def get_quote
  	@quote ||= Quote.includes(:load).friendly.find(params[:id])
  end

  def get_load
  	@load ||= @quote.load
  end

  def quote_params
  	params.require(:quote).permit(:load_id, :offered_date, :offered_vehicle_load_type_id, :offered_vehicle_type_id, :offered_vehicle_quantity, :offered_price)
  end

end

app/helpers/admins/quotes_helper.rb
module Admins::QuotesHelper
end

app/helpers/transporters/quotes_helper.rb
module Transporters::QuotesHelper
end

app/views/admins/quotes/_form.html.erb
<% provide(:title, " Edit Quote") %>
<%= render 'shared/admin_breadcrumbs' %>
<div class="row">
	<%= form_for [:admins, @quote],  :url => url_for(:controller => 'admins/quotes', :action => 'update') do |f| %>
		<div class="panel panel-default">
    	<ul class="list-group">
      	<li class="list-group-item">
        	<div class="row custom-form-row-full">
          	<div class="col-sm-2">
            	<p class="feature_title form-label-title">
              	LOADING DATE
            	</p>
          	</div>
          	<div class="col-sm-2">
            	<div class="form-groupload">
            		<%= f.text_field :offered_date,class: 'form-control custom-form-control',value: @quote.offered_date.strftime("#{@quote.offered_date.day.ordinalize} %b, %Y")%>
             		<div style="color: rgb(204, 0, 0)"><%= show_errors(@quote, :offered_date) %></div>
            	</div>
          	</div>
          </div>
        	
       		<div class="row custom-form-row-full">
          	<div class="col-sm-2">
            	<p class="feature_title form-label-title">
              	TRUCK LOAD
            	</p>
          	</div>
          	<div class="col-sm-2">
            	<div class="form-groupload">
            		<%= f.select :offered_vehicle_type_id, VehicleType.all.collect {|vt| [vt.name, vt.id]}, { prompt: "Select Truck Type" } %>
     						<div style="color: rgb(204, 0, 0)"><%= show_errors(@quote, :offered_vehicle_type_id) %></div>
     					</div>
            </div>
          </div> 
          		
          <div class="row custom-form-row-full">
          	<div class="col-sm-2">
            	<p class="feature_title form-label-title">
              	YOUR QUOTE
            	</p>
          	</div>
          	<div class="col-sm-2">
            	<div class="form-groupload">
            		<%= f.text_field :offered_price,placeholder: "Enter offered price",class: 'form-control custom-form-control'%>
             		<div style="color: rgb(204, 0, 0)"><%= show_errors(@quote, :offered_price) %></div>
            	</div>
          	</div>
          </div>
          	
          <div class="row custom-form-row-full">
						<div class="col-sm-2">
							<%= f.submit 'update', :class => 'btn custom-btn custom_btn custom-add-bordered-btn m-none' %>
						</div>
						<div class="col-sm-2">
							<%= link_to 'cancel', admins_quotes_path, :class => 'btn custom-btn custom_btn custom-add-bordered-btn m-none' %>
						</div>
          </div>
        </li>
      </ul>
    </div>
	<% end %>
</div>

	

app/views/admins/quotes/_quote.html.erb
<% @quotes.each do |quote| %>
	<tr>
		<td><%= quote.transporter_id %></td>
		<td><%= quote.load_id %></td>
		<td><%= link_to quote.load.customer_id, admins_customer_path(quote.load.customer_id) %></td>
		<td><%= quote.load.from_address %></td>
		<td><%= quote.load.to_address %></td>
		<td><%= quote.load.load_type.name %></td>
		<td><%= quote.load.posted_on.try(:strftime, "#{quote.load.posted_on.try(:day).try(:ordinalize)} %b, %Y") || "-" %></td>
		<td><%= quote.offered_date.strftime("#{quote.offered_date.day.ordinalize} %b, %Y") %></td>
		<td><%= quote.vehicle_type.name %></td>
		<td><%= quote.offered_price %></td>
		<td>
			<%= link_to edit_admins_quote_path(quote), class: "action-link", title: "Edit Quote" do %>
				<i class="glyphicon glyphicon-pencil"></i>
			<% end %>
		</td>
		<td>
		<%= link_to cancel_quote_admins_quote_path(quote.slug), class: "action-link", title: "Cancel Quote", method: :put do %>
			<i class="glyphicon glyphicon-remove"></i>
		<% end %>
		</td>
		<td>
			<%= link_to admins_quote_path(quote),class: "action-link" do %>
	      <i class="glyphicon glyphicon-eye-open"></i>
	    <% end %>
		</td>
	</tr>
<% end %>

app/views/admins/quotes/_quotes_details.html.erb
<% @quotes.each do |quote| %>
	<tr>
		<td><%= quote.transporter_id %></td>
		<td><%= quote.load_id %></td>
		<td><%= quote.load.customer_id %></td>
		<td><%= quote.load.from_address %></td>
		<td><%= quote.load.to_address %></td>
		<td><%= quote.load.load_type.name %></td>
		<td><%= quote.load.posted_on.try(:strftime, "#{quote.load.posted_on.try(:day).try(:ordinalize)} %b, %Y") || "-" %></td>
		<td><%= quote.offered_date.strftime("#{quote.offered_date.day.ordinalize} %b, %Y") %></td>
		<td><%= quote.vehicle_type.name %></td>
		<td><%= quote.offered_price %></td>
		<td>
			<%= link_to edit_quote_admins_quote_path(quote), class: "action-link", title: "Edit Quote" do %>
				<i class="glyphicon glyphicon-pencil"></i>
			<% end %>
		</td>
		<td>
		<%= link_to cancel_quote_admins_quote_path(quote.slug), class: "action-link", title: "Cancel Quote", method: :put do %>
			<i class="glyphicon glyphicon-remove"></i>
		<% end %>
	</td>
	</tr>
<% end %>

app/views/admins/quotes/edit.html.erb
<%= render 'form' %>

app/views/admins/quotes/edit_quote.html.erb
<% provide(:title, " Edit Quote") %>
<%= render 'shared/admin_breadcrumbs' %>
<div class="row">
	<%= form_for [:admins, @quote],  :url => url_for(:controller => 'admins/quotes', :action => 'update_quote') do |f| %>
		<div class="panel panel-default">
    	<ul class="list-group">
      	<li class="list-group-item">
        	<div class="row custom-form-row-full">
          	<div class="col-sm-2">
            	<p class="feature_title form-label-title">
              	LOADING DATE
            	</p>
          	</div>
          	<div class="col-sm-2">
            	<div class="form-groupload">
            		<%= f.text_field :offered_date,class: 'form-control custom-form-control',value: @quote.offered_date.strftime("#{@quote.offered_date.day.ordinalize} %b, %Y")%>
             		<div style="color: rgb(204, 0, 0)"><%= show_errors(@quote, :offered_date) %></div>
            	</div>
          	</div>
          </div>
        	
       		<div class="row custom-form-row-full">
          	<div class="col-sm-2">
            	<p class="feature_title form-label-title">
              	TRUCK LOAD
            	</p>
          	</div>
          	<div class="col-sm-2">
            	<div class="form-groupload">
            		<%= f.select :offered_vehicle_type_id, VehicleType.all.collect {|vt| [vt.name, vt.id]}, { prompt: "Select Truck Type" } %>
     						<div style="color: rgb(204, 0, 0)"><%= show_errors(@quote, :offered_vehicle_type_id) %></div>
     					</div>
            </div>
          </div> 
          		
          <div class="row custom-form-row-full">
          	<div class="col-sm-2">
            	<p class="feature_title form-label-title">
              	YOUR QUOTE
            	</p>
          	</div>
          	<div class="col-sm-2">
            	<div class="form-groupload">
            		<%= f.text_field :offered_price,placeholder: "Enter offered price",class: 'form-control custom-form-control'%>
             		<div style="color: rgb(204, 0, 0)"><%= show_errors(@quote, :offered_price) %></div>
            	</div>
          	</div>
          </div>
          	
          <div class="row custom-form-row-full">
						<div class="col-sm-2">
							<%= f.submit 'save', :class => 'btn custom-btn custom_btn custom-add-bordered-btn m-none' %>
						</div>
						<div class="col-sm-2">
							<%= link_to 'cancel', admins_quotes_path, :class => 'btn custom-btn custom_btn custom-add-bordered-btn m-none' %>
						</div>
          </div>
        </li>
      </ul>
    </div>
	<% end %>
</div>
	

app/views/admins/quotes/index.html.erb
<div class="row">
  <div class=" col-xs-12 col-sm-12">
    <div class="page_title view-page-title">
      <h2 class="mt-10 col-sm-1 p-none">Quotes</h2>
      <div class="col-sm-4 add-more-left post_load">
        <%#= link_to "Post New Load", new_admins_load_path %>
      </div>
      <%= render 'admins/load_and_quote_header' %>
    </div>
   </div>
</div>
<%#= link_to "Post New Load", new_admins_load_path, class: "btn btn-primary" %>
<!-- <h3>Loads</h3> -->
<div class="row table-contents-wrapper table-records-wrapper">
  <div class="col-xs-12 revenue-table-wrapper">
    <div class="row search-wrapper">
      <div class="col-sm-6 revenue-search-box">
        <form class="form-inline revenue-table-form view-record-form">
          <label>Search</label>
          <input type="text" class="form-control search-box" name="search" id="search">
        </form>
      </div>
      <div class="col-sm-6 revenue-search-box">
        <div class="dropdown">
          <button onclick="myFunction()" class="dropbtn">Quote Type</button>
          <div id="myDropdown" class="dropdown-content">
            <%= link_to "All",admins_quotes_path %>
            <%= link_to "Drafted",admins_quotes_path(status: 'drafted') %>
            <%= link_to "Submitted",admins_quotes_path(status: 'submitted')%>
            <%= link_to "Withdrawed",admins_quotes_path(status: 'withdrawed')%>
            <%= link_to "Accepted",admins_quotes_path(status: 'accepted')%>
          </div>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-hover revenue-table">
        <thead class="bg-color-pink">
          <tr>
            <th>TRANSPORTER ID</th>
            <th>LOAD ID</th>
            <th>CUSTOMER ID</th>
            <th>FROM</th>
            <th>TO</th>
            <th>LOAD TYPE</th>
            <th>POSTED ON</th>
            <th>LOADING DATE</th>
            <th>TRUCK LOAD</th>
            <th>YOUR QUOTE</th>
            <th colspan="3">ACTIONS</th>
          </tr>
        </thead>
        <tbody>
          <%= render 'quote' %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/quotes/quotes_details.html.erb
<div class="row">
  <div class=" col-xs-12 col-sm-12">
    <div class="page_title view-page-title">
      <h2 class="mt-10 col-sm-1 p-none">Loads</h2>
      <div class="col-sm-4 add-more-left post_load">
        <%= link_to "Post New Load", new_admins_load_path %>
      </div>
      <div class="col-sm-6 add-more-right">
        <%= link_to "Load",admins_loads_path, class: 'btn custom-head-add-bordered-btn' %>
        <%= link_to "Quotes",admins_quotes_quotes_details_path, class: 'btn custom-head-add-bordered-btn' %>
      </div>
    </div>
   </div>
</div>
<%#= link_to "Post New Load", new_admins_load_path, class: "btn btn-primary" %>
<!-- <h3>Loads</h3> -->
<div class="row table-contents-wrapper table-records-wrapper">
  <div class="col-xs-12 revenue-table-wrapper">
  	<div class="row search-wrapper">
      <div class="col-sm-6 revenue-search-box">
        <form class="form-inline revenue-table-form view-record-form">
          <label>Search</label>
          <input type="text" class="form-control search-box" name="search" id="search">
        </form>
      </div>
      <div class="col-sm-6 revenue-search-box">
        <div class="dropdown">
          <button onclick="myFunction()" class="dropbtn">Load Type</button>
          <div id="myDropdown" class="dropdown-content">
            <%= link_to "Submitted",admins_loads_path %>
            <%= link_to "Not Submitted",admins_loads_path(load_status: 'drafted')%>
          </div>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-hover revenue-table">
        <thead class="bg-color-pink">
					<tr>
            <th>TRANSPORTER ID</th>
						<th>LOAD ID</th>
						<th>CUSTOMER ID</th>
						<th>FROM</th>
						<th>TO</th>
						<th>LOAD TYPE</th>
						<th>POSTED ON</th>
						<th>LOADING DATE</th>
						<th>TRUCK LOAD</th>
            <th>YOUR QUOTE</th>
						<th colspan="2">ACTIONS</th>
					</tr>
				</thead>
				<tbody>
          <%= render 'quotes_details' %>
        </tbody>
			</table>
		</div>
  </div>
</div>